apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: nodejs
  labels:
    app: nodejs-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-argocd
          image: shreedhar4037/nodejs-circleci:3
          ports:
            - name: http
              containerPort: 1337
---------

apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: nodejs
  labels:
    app: nodejs-service
spec:
  type: loadbalancer
  ports:
    - port: 80
      targetPort: 1337
  selector:
    app: nodejs-app
