apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  
  labels:
    app: nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs-argocd
          image: shreedhar4037/nodejs-circleci:3
          ports:
            - name: http
              containerPort: 1337
####
apiVersion: v1
kind: Service
metadata:
  name: nodejs
 
  labels:
    app: nodejs
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 1337
  selector:
    app: nodejs
